### ISSUE TITLE
Firefox extension ask for access your data for all websites

### ISSUE THREAD

**Issue by kaushalyap** [roedesh/copyguard#3]
I checked Firefox version of the extension it use [Access your data for all websites](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-your-data-for-all-websites) permission which seems invasive.

![Screenshot from 2020-12-29 21-18-47](https://user-images.githubusercontent.com/24698778/103296470-2aa61800-4a1c-11eb-88f9-d071586bc64a.png)

But Chrome extension does not use a such permission

![Screenshot from 2020-12-29 21-25-33](https://user-images.githubusercontent.com/24698778/103296684-912b3600-4a1c-11eb-8df9-4432426353a9.png)

**Comment by roedesh** [comment]
It seems that Firefox shows that warning is because my extension can inject a content script into any tab, whenever it wants. 

There is a less intrusive permission called `activeTab` which does not show that warning, but requires the user to perform an action within that tab before my extension can inject its script. This is a problem because:

- If the user forgets to perform such an action, my extension will not inject its script, and you won't receive a warning when your clipboard data was altered. This seems a bit counter intuitive to me.
- Ideally my script needs to run before any other scripts, due to event bubbling

Perhaps I should add an explanation to the Firefox extension for the "Access your data for all websites" permission?

I'm open to suggestions.

**Comment by kaushalyap** [comment]
> There is a less intrusive permission called activeTab which does not show that warning, but requires the user to perform an action within that tab before my extension can inject its script.

Why do you need to inject a script? Cannot you detect [clipboard changes using `clipboardRead`, `clipboardWrite` permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions)?

**Comment by roedesh** [comment]
I need the content script to listen for the "copy" event and to get the current text selection.

**Comment by kaushalyap** [comment]
Seems like [Firefox clipboard API is not ready yet](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard)

> The Clipboard interface implements the Clipboard API, providing—if the user grants permission—both read and write access to the contents of the system clipboard. The Clipboard API can be used to implement cut, copy, and paste features within a web application.

**Comment by kaushalyap** [comment]
I wonder how you do things in Chrome extension? Do you inject a script in there also?

**Comment by roedesh** [comment]
> I wonder how you do things in Chrome extension? Do you inject a script in there also?

Yes, the extension works identical in all versions (Chrome, Firefox and Edge). I use the [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) so its a single code base for all versions.

**Comment by kaushalyap** [comment]
Okay you may add a note about Firefox permission to the README

**Comment by roedesh** [comment]
> Would it be possible for the "copy to clipboard" user action to be the action that triggers the script to be injected? Or would it be too late?

Unfortunately the browser extension API's do not provide such a feature. It would also be too late indeed (although only for the first time you copy) as the event listener will be added after the copy has been done.

The only way to inject the content script on all pages automatically, is to set the the allowed origins to `http` and `https` addresses, which, in Firefox, translates to "Access your data for all websites".

If I disable the automatic injection, it will get rid of the warning in Firefox, but the user will have to do a certain action like clicking on the browser extension icon, before I can inject the content script. They will have to do this on every visit.

**Comment by Gitoffthelawn** [comment]
Thanks.  That makes good sense.

I can't think of a really great solution, but I did come up with a possibility:

Firefox allows developers to set *on-demand* permissions for extensions.  By default, the extension could *not* ask for the "Access your data for all websites" permission; instead it can provide a toolbar button or context menuitem to activate the extension on the current page.  Separately, there can be an option to enable the extension for all pages.  When the user enables that option, Firefox will prompt for the "Access you data for all websites" permission.

I don't love the above because it's a bit clunky (IMO), but it might be the only possibility (besides keeping things how they are).

**Comment by Gitoffthelawn** [comment]
Has anything changed with the browser APIs that would allow an improvement per the OP's request?
